version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: quantfolio_mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: quantfolio
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
